// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5R7m4ODvjxa7MDsVNQvI--FC1iPaVIpM',
    appId: '1:895511832565:android:28a720b1745f6fee3262bc',
    messagingSenderId: '895511832565',
    projectId: 'dars-f31ed',
    databaseURL: 'https://dars-f31ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dars-f31ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSzAhyp_kYefSBjM3WrMXsmck1GZcH1XY',
    appId: '1:895511832565:ios:0d1adf706a83a97a3262bc',
    messagingSenderId: '895511832565',
    projectId: 'dars-f31ed',
    databaseURL: 'https://dars-f31ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dars-f31ed.appspot.com',
    iosBundleId: 'com.example.dars12',
  );

}